# Generated by Django 6.0.7 on 2026-07-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(help_text='The listing being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing'),
        ),
    ]
