# Generated by Django 6.0.7 on 2026-07-10 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='Image URL (e.g. Cloudinary)', max_length=1000)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_cover', models.BooleanField(default=False, help_text='Main/cover image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-is_cover', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('cabin', 'Cabin'), ('condo', 'Condo'), ('cottage', 'Cottage'), ('studio', 'Studio'), ('loft', 'Loft'), ('townhouse', 'Townhouse'), ('boat', 'Boat'), ('treehouse', 'Treehouse'), ('other', 'Other')], default='apartment', max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in USD', max_digits=10)),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('beds', models.PositiveIntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True, help_text='Visible to guests')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
